---
version: '2.4'

services:
  remy_pizza_place:
    image: remy_pizza_place
    build: .
    container_name: remy_pizza_place
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - GAZEBO_MASTER_IP=127.0.0.1
      - GAZEBO_MASTER_URI=127.0.0.1:11345
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    stop_signal: SIGINT
    volumes:
      - /tmp/.gazebo/:/root/.gazebo/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./simulation_bringup/config:/opt/ros/overlay_ws/src/simulation_bringup/config
