panda1:
  position_joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - panda1_joint1
      - panda1_joint2
      - panda1_joint3
      - panda1_joint4
      - panda1_joint5
      - panda1_joint6
      - panda1_joint7
    constraints:
      goal_time: 0.5
      panda1_joint1: { goal: 0.05}
      panda1_joint2: { goal: 0.05}
      panda1_joint3: { goal: 0.05}
      panda1_joint4: { goal: 0.05}
      panda1_joint5: { goal: 0.05}
      panda1_joint6: { goal: 0.05}
      panda1_joint7: { goal: 0.05}

  effort_joint_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - panda1_joint1
      - panda1_joint2
      - panda1_joint3
      - panda1_joint4
      - panda1_joint5
      - panda1_joint6
      - panda1_joint7
    gains:
      panda1_joint1: { p: 600, d: 30, i: 0 }
      panda1_joint2: { p: 600, d: 30, i: 0 }
      panda1_joint3: { p: 600, d: 30, i: 0 }
      panda1_joint4: { p: 600, d: 30, i: 0 }
      panda1_joint5: { p: 250, d: 10, i: 0 }
      panda1_joint6: { p: 150, d: 10, i: 0 }
      panda1_joint7: { p: 50, d: 5, i: 0 }
    constraints:
      goal_time: 0.5
      panda1_joint1: { goal: 0.05}
      panda1_joint2: { goal: 0.05}
      panda1_joint3: { goal: 0.05}
      panda1_joint4: { goal: 0.05}
      panda1_joint5: { goal: 0.05}
      panda1_joint6: { goal: 0.05}
      panda1_joint7: { goal: 0.05}

  franka_state_controller:
    type: franka_control/FrankaStateController
    arm_id: panda1
    publish_rate: 30  # [Hz]
    joint_names:
      - panda1_joint1
      - panda1_joint2
      - panda1_joint3
      - panda1_joint4
      - panda1_joint5
      - panda1_joint6
      - panda1_joint7

panda2:
  position_joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - panda2_joint1
      - panda2_joint2
      - panda2_joint3
      - panda2_joint4
      - panda2_joint5
      - panda2_joint6
      - panda2_joint7
    constraints:
      goal_time: 0.5
      panda2_joint1: { goal: 0.05}
      panda2_joint2: { goal: 0.05}
      panda2_joint3: { goal: 0.05}
      panda2_joint4: { goal: 0.05}
      panda2_joint5: { goal: 0.05}
      panda2_joint6: { goal: 0.05}
      panda2_joint7: { goal: 0.05}

  effort_joint_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - panda2_joint1
      - panda2_joint2
      - panda2_joint3
      - panda2_joint4
      - panda2_joint5
      - panda2_joint6
      - panda2_joint7
    gains:
      panda2_joint1: { p: 600, d: 30, i: 0 }
      panda2_joint2: { p: 600, d: 30, i: 0 }
      panda2_joint3: { p: 600, d: 30, i: 0 }
      panda2_joint4: { p: 600, d: 30, i: 0 }
      panda2_joint5: { p: 250, d: 10, i: 0 }
      panda2_joint6: { p: 150, d: 10, i: 0 }
      panda2_joint7: { p: 50, d: 5, i: 0 }
    constraints:
      goal_time: 0.5
      panda2_joint1: { goal: 0.05}
      panda2_joint2: { goal: 0.05}
      panda2_joint3: { goal: 0.05}
      panda2_joint4: { goal: 0.05}
      panda2_joint5: { goal: 0.05}
      panda2_joint6: { goal: 0.05}
      panda2_joint7: { goal: 0.05}

  franka_state_controller:
    type: franka_control/FrankaStateController
    arm_id: panda2
    publish_rate: 30  # [Hz]
    joint_names:
      - panda2_joint1
      - panda2_joint2
      - panda2_joint3
      - panda2_joint4
      - panda2_joint5
      - panda2_joint6
      - panda2_joint7
